### ISSUE TITLE
Request to add paper

### ISSUE THREAD

**Issue by HarmanDotpy** [jeffhj/LM-reasoning#1]
Hi, 
great work/repo!

Please consider adding our work on deductive/logical reasoning.

**FaiRR: Faithful and Robust Deductive Reasoning over Natural Language**, ACL 2022 (arxived on: 19 Mar 2022)
[paper link](https://arxiv.org/abs/2203.10261)
Soumya Sanyal, Harman Singh, Xiang Ren

**Comment by jeffhj** [comment]
Add it. Good work :)

**Comment by HarmanDotpy** [comment]
thanks, closing
