### ISSUE TITLE
In case you were planning to expand on inductive reasoning

### ISSUE THREAD

**Issue by kanishkamisra** [jeffhj/LM-reasoning#3]
Thanks for synthesizing such a fast growing list of papers on LLMs and reasoning! I also appreciate you writing about reasoning types that go beyond deductive! 

I have a few papers that touch on inductive reasoning in humans and models in case you'd like to expand on that topic in the survey, though disclaimer: these only deal with what you consider to be small LMs (though they are model agnostic).

Misra, 2022 (AAAI Doctoral Consortium 2022): On Semantic Cognition, Inductive Generalization, and Language Models
https://ojs.aaai.org/index.php/AAAI/article/view/21584

Misra et al., 2022 (CogSci 2022): A Property Induction Framework For Neural Language Models:
https://arxiv.org/abs/2205.06910

Misra et al., 2021 (CogSci 2021): Do language models learn typicality judgments from text? (exp 2 is the first analysis of LMs on Inductive Reasoning)
https://arxiv.org/abs/2105.02987

Other papers that should be included in case you do decide to pursue this route:

Han et al., 2022 (CogSci 2022): Human-like property induction is a challenge for large language models 
https://psyarxiv.com/6mkjy/

Yang et al., 2022: Language Models as Inductive Reasoners
https://arxiv.org/abs/2212.10923

**Comment by jeffhj** [comment]
Hi @kanishkamisra, thanks for your information!

I think these papers are interesting, but I'm not currently planning to expand to inductive reasoning -- reasoning is a broad concept that encompasses various forms, so we need to have a focus.

I will briefly mention these papers in the next version of the survey and keep this issue open (if you don't want to close it) to be visible to readers :)

**Comment by kanishkamisra** [comment]
This makes sense! No worries -- I will close the issue to avoid crowding!
