### ISSUE TITLE
Request to add a new survey

### ISSUE THREAD

**Issue by OakYU** [jeffhj/LM-reasoning#8]
Hi, thanks for your contributions to collating large language model reasoning papers! 
Recently, we release a reasoning survey on natural language reasoning mainly from another perspective: the reasoning paradigm (end-to-end, forward, and backward). 

Here are our survey and repository:
Nature Language Reasoning, A Survey
https://arxiv.org/pdf/2303.14725.pdf
https://github.com/FreedomIntelligence/ReasoningNLP

I believe our surveys and repositories can complementarily help people better understand the reasoning!

**Comment by jeffhj** [comment]
Interesting survey. Add it.
